/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.12.0
 *
 * Project: 'lp_audio.release+E1C-HE' 
 * Target:  'release+E1C-HE' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"

/* ARM::CMSIS-Compiler:STDOUT:Custom@1.0.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* AlifSemiconductor::BSP:External peripherals:WM8904 CODEC@2.0.0 */
#define RTE_Drivers_WM8904_CODEC   1           /* Driver */
/* AlifSemiconductor::CMSIS Driver:I2C@2.0.0 */
#define RTE_Drivers_I2C              /* Driver I2C */
/* AlifSemiconductor::CMSIS Driver:SAI@2.0.0 */
#define RTE_Drivers_SAI              /* Driver SAI */
/* AlifSemiconductor::CMSIS Driver:USART@2.0.0 */
#define RTE_Drivers_USART               /* Driver UART  */
/* AlifSemiconductor::Device:SOC Peripherals:DMA@2.0.0 */
#define RTE_Drivers_DMA                   /* Driver DMA*/
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@2.0.0 */
#define RTE_Drivers_IO              /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:PDM@2.0.0 */
#define RTE_Drivers_PDM              /* Driver PDM */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@2.0.0 */
#define RTE_Drivers_LL_PINCONF              /* Driver PinPAD and PinMux */


#endif /* RTE_COMPONENTS_H */
